### ISSUE TITLE
Error on publish

### ISSUE THREAD

**Issue by ghost** [goodeggs/npm-copy#1]
I'm trying to copy my corp's private npmjs repositories to an on-premise hosting (using Nexus OSS 3.3.0), using this I do

```
npm-copy --from https://registry.npmjs.org --from-token <token-taken-from-dotnpmrc> --to http://nexus.my.corps.lan:8081/repository/npm-my-corp --to-username admin --to-password <my-admin-password @my-corp%2fapp-status @my-corp%2fapp-update
```

which gives the following errors

    info attempt registry request try #1 at 12:56:28 PM
    http request GET https://registry.npmjs.org/@my-corp%2fapp-status
    http 200 https://registry.npmjs.org/@my-corp%2fapp-status
    info attempt registry request try #1 at 12:56:28 PM
    http request GET http://nexus.my.corps.lan:8081/repository/npm-my-corp/@my-corp%2fapp-status
    http 404 http://nexus.my.corps.lan:8081/repository/npm-my-corp/@my-corp%2fapp-status
    info attempt registry request try #1 at 12:56:28 PM
    http fetch GET https://registry.npmjs.org/@my-corp/app-status/-/app-status-1.0.0.tgz
    http fetch 200 https://registry.npmjs.org/@my-corp/app-status/-/app-status-1.0.0.tgz
    Error: auth required for publishing
        at RegClient.publish (/usr/lib/node_modules/npm-copy/node_modules/npm-registry-client/lib/publish.js:30:14)
        at RegClient.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/fibrous/lib/fibrous.js:50:17)
        at RegClient.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/fibrous/lib/fibrous.js:66:29)
        at Object.publish (/usr/lib/node_modules/npm-copy/node_modules/fibrous/lib/fibrous.js:101:47)
        at /usr/lib/node_modules/npm-copy/lib/cli.js:83:26
        at /usr/lib/node_modules/npm-copy/lib/cli.js:100:7
        at /usr/lib/node_modules/npm-copy/node_modules/fibers/future.js:467:21

**Comment by dperuo** [comment]
For what it's worth, we cloned this project and made some updates: https://www.npmjs.com/package/@appsweet-co/npm-carbon

We will actively maintain the new `@appsweet-co/npm-carbon` package.
