### ISSUE TITLE
Do do not try to vopy deleted versions

### ISSUE THREAD

**Issue by johgoe** [goodeggs/npm-copy#2]
npmjs.cpm allows to delete(unpublish) versions in private repositories. For this versions the fetch of the package fails and the copy process stops with an error.

**Comment by dperuo** [comment]
For what it's worth, we cloned this project and made some updates: https://www.npmjs.com/package/@appsweet-co/npm-carbon

We will actively maintain the new `@appsweet-co/npm-carbon` package.
