### ISSUE TITLE
Do not enforce credentials on --from

### ISSUE THREAD

**Issue by romanzenka** [goodeggs/npm-copy#8]
Our source repository is somewhat broken and will actually fail as soon as you try to authenticate to it (Nexus).

Can there be a way to simply not specify credentials to from? 

If --from credentials are not specified, the auth parameter will be omitted. This would work great for public --from repositories.

**Comment by missingdays** [comment]
Any updates on this? It's inconvenient that the authentication is required to read from the repository, since some repositories have public access and don't need any credentials to read from them

**Comment by romanzenka** [comment]
@missingdays I ended up deleting part of the source code for my purposes, but I do not have anything official, PR-able at the moment.

**Comment by bobzoller** [comment]
We no longer have a use for npm-copy and as such, don't have the bandwidth
to maintain it.  I'm happy to help facilitate a transfer to a new owner if
someone is interested.
